language: java

# Make sure the whole app can be built, not just compiled
# (checks for pom.xml errors)
script: mvn package

# Install our dependencies
before_install:
  # Don't mess with the main repository
  - export MAIN_REPO="$(pwd)"
  - cd ..

  # Get some shared libs or else the SDK executables aren't found
  - sudo apt-get update -qq
  - sudo apt-get install -qq ia32-libs ia32-libs-multiarch libgphoto2-2:i386 libsane:i386 libgd2-xpm:i386

  # Install what we need from the SDK
  - wget -O android-sdk-linux.tgz http://dl.google.com/android/android-sdk_r21.1-linux.tgz
  - tar xzf android-sdk-linux.tgz
  - export ANDROID_HOME="$(pwd)/android-sdk-linux"
  - export PATH="${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools"
  - android update sdk --no-ui --force --filter platform-tools,android-16,extra-android-support

  # Install what we need to Maven
  - git clone git://github.com/mosabua/maven-android-sdk-deployer.git
  - cd maven-android-sdk-deployer
  - mvn install -N
  - cd extras
  - mvn install -N
  - cd compatibility-v4
  - mvn install
  - cd ../compatibility-v7-gridlayout
  - mvn install
  - cd ../../..

  # Come back into main repository
  - cd ${MAIN_REPO}
