language: java

# Install our dependencies
before_install:
  # Copy template passwords file to local file
  - cp "passes.template.xml" "passes.local.xml"

  # Don't mess with the main repository
  - export MAIN_REPO="$(pwd)"
  - cd ..

  # Get some shared libs or else the SDK executables aren't found
  - sudo apt-get update -qq
  - sudo apt-get install -qq ia32-libs ia32-libs-multiarch libgphoto2-2:i386 libsane:i386 libgd2-xpm:i386

  # Install what we need from the SDK
  - wget -O android-sdk-linux.tgz http://dl.google.com/android/android-sdk_r23-linux.tgz
  - tar xzf android-sdk-linux.tgz
  - export ANDROID_HOME="$(pwd)/android-sdk-linux"
  - export PATH="${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools"
  # Partition downloads into licence groups, otherwise `echo "y"` doesn't work
  - echo "y" | android update sdk --no-ui --force --filter build-tools-20.0.0,android-16,platform-tools,extra-android-support
  - echo "y" | android update sdk --no-ui --force --filter extra-android-m2repository

  # Come back into main repository
  - cd ${MAIN_REPO}
